### ISSUE TITLE
Explore existing DwC tools

### ISSUE THREAD

**Issue by fontikar** [AtlasOfLivingAustralia/galaxias#1]
Will be testing and playing around with `bdDwC` (GNU General Public License) to see how we can springboard from their code base

The creators/maintainers: https://bd-r.github.io/The-bdverse/the-bdverse-team.html
The repo: https://github.com/bd-R/bdDwC
The app's documentation: https://bd-r.github.io/bdDwC-guide/index.html
The publication: https://biss.pensoft.net/articles.php?id=20486

Will do this on a seperate branch `explore`

**Comment by fontikar** [comment]
Initial thoughts: 
- Installation had hiccups, some dependencies were out-of-date and required a few manual installs of specific packages to get it working (Minor issue)
- Running their app was simple but some of the core functions (e.g. renaming columns) is missing from the interface
- Interface uses a "Darwin Core Dictionary" - "a lookup table that accumulates different variations in DwC field names from different publishers" but I am unable to find this at the moment
   - Dictionary was inspired by: https://github.com/kurator-org/kurator-validation/wiki/CSV-File-Darwinizer

**Comment by fontikar** [comment]
Will try to clone `finch` locally and rebuild it and test it out

Repo: https://github.com/ropensci-archive/finch

Limited documentation, no working website or vignette.

**Comment by mjwestgate** [comment]
This was all useful content, but I think we're past the stage where this needs to be an open issue :)
