### ISSUE TITLE
explore pointblank 

### ISSUE THREAD

**Issue by shandiya** [AtlasOfLivingAustralia/galaxias#3]
Explore the viability of using the {pointblank} package for narrowing down or matching columns from user-supplied datasets to Darwin Core Archive column names

**Comment by shandiya** [comment]
Use {pointblank} for the following: 
Are required data fields missing? (basisOfRecord, eventDate, scientificName)
Goal: Identify which required fields are missing, if any and prompt user to put these in their csv and restart the process.
Steps required:
Detect whether basisOfRecord, eventDate, scientificName exist in tibble
Output: Logical denotes whether required fields are missing and if TRUE, vector of which ones are missing so user can add in and restart workflow

**Comment by mjwestgate** [comment]
Currently (2024-06) using own functions, rather than pointblank.
