### ISSUE TITLE
Explore Shiny structure and components

### ISSUE THREAD

**Issue by fontikar** [AtlasOfLivingAustralia/galaxias#4]
Want to get family with [shiny components](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html), so we can draft the interface and work backwards! 

Some ideas: 
- Drag drop box for .csv
- Column matching after our package takes a "best guess" 
- Editor window for .md and knit to preview what user supplied
- Survey like form for questions for basis of record, spatial precision, kingdom etc
- Option to preview eml.xml 
- Option to download zipped DwCA

Will work off a `shiny` branch from main

**Comment by mjwestgate** [comment]
Closed as decided not to pursue Shiny interfaces at this point
